site_name: Channels Hub
site_url: https://channels.readthedocs.io/
theme:
  name: material
  logo: assets/CHANNELS.png
  custom_dir: docs/assets/
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: light blue
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: deep orange

nav:
  - Home: index.md
  - API:
    - Overview: API/API.md
    - Endpoints: API/api-endpoints.md
    - Authentication: API/api-auth.md
  - EBO:
    - Overview: EBO/EBO.md
    - Architecture: EBO/Architecture.md
  - Mobile:
    - Overview: Mobile/Mobile.md

extra_css:
  - assets/custom.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
